language: python
sudo: false

matrix:
  include:
    - python: "3.6"

install:
  - conda update --yes conda
  # Append the conda-forge channel, instead of adding it. See:
  # https://github.com/conda-forge/conda-forge.github.io/issues/232)
  - conda config --append channels conda-forge
  - conda create -n testenv --yes $DEPS nose python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # only install pip if there are pip dependencies
  # - |
  #   if [ -n "$DEPSPIP" ]; then
  #       conda install -n testenv --yes pip
  #       pip install $DEPSPIP
  #   fi
  - python -m pip install .


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ];
    then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
    # for running the GUI
    - xvfb-run --server-args="-screen 0 1024x768x24" make test
    # the actual tests
    - nosetests --nologcapture
